# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('U_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('U_Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255, unique=True)),
                ('Password', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['U_Id'],
                'db_table': 'users',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
