# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('G_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('G_Name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['G_Id'],
                'db_table': 'groups',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Group_Transaction',
            fields=[
                ('GT_Id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('G_Id', models.IntegerField()),
                ('T_Id', models.IntegerField()),
            ],
            options={
                'ordering': ['GT_Id'],
                'db_table': 'group_transactions',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G_Id', models.IntegerField()),
                ('U_Id', models.IntegerField()),
            ],
            options={
                'db_table': 'members',
            },
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
