#CREATE ALL TABLES
CREATE TABLE USERS (U_Id int NOT NULL, U_Name varchar(255) NOT NULL, Email varchar(255) NOT NULL, Password varchar(255) NOT NULL, PRIMARY KEY (U_Id));
CREATE TABLE GROUPS (G_Id int NOT NULL, G_Name varchar(255), PRIMARY KEY (G_Id));
CREATE TABLE MEMBERS (G_Id int NOT NULL, U_Id int NOT NULL, Foreign Key (G_Id) REFERENCES GROUPS(G_Id), Foreign Key (U_Id) REFERENCES USERS(U_Id));
CREATE TABLE TRANSACTIONS (T_Id int NOT NULL, Sender_Id int NOT NULL, Receiver_Id int NOT NULL, Category varchar(255), Memo nvarchar(255), Amount numeric(15,2) NOT NULL, Date datetime NOT NULL, PRIMARY KEY (T_Id), Foreign Key (Sender_Id) REFERENCES USERS(U_Id), Foreign Key (Receiver_Id) REFERENCES USERS(U_Id));
CREATE TABLE GROUP_TRANSACTIONS (GT_Id int NOT NULL, G_Id int NOT NULL, T_Id int NOT NULL, PRIMARY KEY (GT_Id), FOREIGN KEY (G_Id) REFERENCES GROUPS(G_Id), FOREIGN KEY (T_Id) REFERENCES TRANSACTIONS(T_Id));
